### ISSUE TITLE
Not working with Google Drive Content URI

### ISSUE THREAD

**Issue by okwei2000** [gjoris/cordova-filepath-resolver#1]
I'm using this plugin to resolve the contentURI sent in when my app is open by 'share' menu from another app. Most app seems ok, except the contentURI sent by Google Drive. the URI looks the following:

content://com.google.android.apps.docs.storage.legacy/enc%3D2Rb92KRZttiVwkmrkPK6QILQHWhqH_EF8SLcrB952h84UjM9%0A

And I got an error message "Unable to resolve filesystem path."

Could this be related the format of the URI sent by google drive?

**Comment by okwei2000** [comment]
Could this related to 
http://stackoverflow.com/questions/25171246/open-a-google-drive-file-content-uri-after-using-kitkat-storage-access-framework

**Comment by gjoris** [comment]
At this point, this plugin is to resolve a path to a local file. Google Drive files are not local files, and are not supported at this point.

**Comment by gjoris** [comment]
I have closed this, since it is not an issue for this plugin, but I'll look into the matter.

**Comment by okwei2000** [comment]
I think google drive downloads the file first then share it.. for example, when you share a google doc file, it generate a PDF version and then share it to the other app.. so the content URI should be pointing to a local file.
